vimeo/dials

deep_copy_test.go, dials.go
The builder was never extensively used and is mostly replaced by the
Mangler structures.  Just remove that for now.  And simplify some test
code that the linter was complaining about.
=> Remove Builder and Cleanup Tests

dials.go, env/env_test.go, file/file_test.go, flag/flag_test.go, integrationtests/case_conversion_transformer_test.go, json/json_test.go, sourcewrap/blank_test.go, toml/toml_test.go, yaml/yaml_test.go
Rather than having `View` be a type, make `Dials` the actual root type
and have `View` be a method that returns the current "view" of the
configuration.
This will be followed up with another PR that introduces `Fill` which
will take a pointer to a config structure to eliminate having to do the
type assert.
=> Renaming "View"

ez/ez.go, file/file.go, file/file_test.go
Two changes:
- Make optional arguments to the `NewWatchingSource` constructor variadic options
- Add an `ez` subpackage with a wrapper for creating a flag source, file source and env source and appropriately using the `blank` source for picking the appropriate configuration file to read.
If the new function is considered simple enough, we can add a few more "simple" functions to the `ez` package. (note: this has to be its own subpackage because of circular dependencies involving the `Source` interface, otherwise).
=> Simplify common-case setup

transform/flatten_mangler.go, transform/flatten_mangler_test.go
Add a fix to handle embedded fields' names in flatten mangler at the top level and add a test for it. Before, it would add the name of the embedded field name to the nested fields in that structs and now that prevents the name addition if the field is anonymous. We handled it for embedded fields in nested structs, just not in the top level struct
=> Handle Embedded fields at top level

.github/workflows/go.yml, go.mod, tagformat/caseconversion/case_conversion.go, tagformat/caseconversion/case_conversion_test.go
1. Have DecodeGolangCamelCase support snake case since many instances of Go naming use snake case.
2. Ensure a trailing underscore in snake case decodes doesn't return an empty string in the decoded array
3. Group the decode functions together in the test
4. Remove support for go 1.12
=> Support Snake Case

transform/flatten_mangler.go, transform/flatten_mangler_test.go
Add a tag to keep track of the path to the nested struct fields in the original struct. This will be used in the flags package so we can set the default value for the flags. The tag value will the comma separated string and we can convert the string to a slice of ints to get the value of the field by index (example in `TestTopLevelEmbed` test)
=> Add dialsfieldpath tag in flatten mangler

transform/flatten_mangler.go, transform/flatten_mangler_test.go
When creating a dials tag based on the field name, decode the field name assuming it's using go camel case and append that to the tags. This way, flags/pflags will have appropriate lowercased flag names based off the dials tags
=> flatten mangler: Decode Field Names for tags

flag/flaghelper/complex.go, flag/flaghelper/strings.go, go.sum, parse/complex.go, parse/complex_test.go, parse/map.go, parse/map_string_string_slice.go, parse/map_string_string_slice_test.go, parse/map_test.go, parse/number.go, parse/parse_string.go, parse/split_map.go, parse/split_string_slice.go, parse/string_set.go, parse/string_set_test.go, parse/string_slice.go, parse/string_slice_test.go, transform/string_casting_mangler.go, transform/string_casting_mangler_test.go
Rename `parsestring` to `parse` and rename functions to remove the `Parse` prefix
=> Parsestring renaming

common/tags.go, env/env.go, flag/flag.go, flag/flag_test.go, json/json.go, overlay.go, pflag/pflag.go, pflag/pflag_test.go, ptrify/ptrify.go, ptrify/ptrify_test.go, tagformat/expand_tags_test.go, tagformat/reformat_tags.go, tagformat/reformat_tags_test.go, toml/toml.go, transform/flatten_mangler.go, transform/flatten_mangler_test.go, yaml/yaml.go
Any field with a `dials` tag value of "-" will be skipped during pointerification. Additionally, `pflag` and `flag` package will not register flags for fields with "-" tag values. Note that nested struct fields will still be registered for pflag/flag packages.
Move `dials` tag to the `common` package to resolve import cycles
=> Support hyphens

env/env.go, env/env_test.go, tagformat/caseconversion/case_conversion.go, tagformat/caseconversion/case_conversion_test.go
Create a flexible function that is similar to `DecodeGoCamelCase` but also allows hyphens. Use this function for reformat tag mangler in the env source instead of `DecodeGoCamelCase` function so dials tags that have hyphens in them (ex: flag fields) don't return an error while reformatting
=> Flexible tagging decoding

deep_copy.go, deep_copy_test.go, dials.go, overlay.go, overlay_test.go
Deep copy between layers to allow for direct pointer assignment while overlaying.
Make deep-copy safe for use with structs containing self-referential pointers. Use the same method to dedup maps sharing a backing pointer.
=> Overlay: more deep-copies and add deep-copy consistency and recursive struct handling

tagformat/caseconversion/case_conversion.go, tagformat/caseconversion/case_conversion_test.go, transform/flatten_mangler_test.go
Return early when `len(word) ==0` in caseconversion encoding functions. The word slice will be 0 when we have top level embedded structs without any tags (we don't add tags to the embedded structs in the flatten mangler). The encoding functions would panic in 2 different cases. One is when we call `b.Grow(aggregateStringLen(words) + len(words) - 1)` which results in growing by -1. The second place is when we call `b.WriteString(words[0])` with index out of range for an empty slice. 
Add tests for caseconversion and flatten mangler
=> Caseconversion return early

flag/flag.go, flag/flaghelper/marshal_wrapper.go, flag/flaghelper/time.go
- Better default handling for `time.Time` using a custom wrapper struct
- Better default printing for types that use `flaghelper.MarshalWrapper`
=> flag/flaghelper: tweaks to improve PrintDefaults output

dials.go, dials_test.go
Make a private copy of the default config (template) provided as an
argument to `Config` to avoid surprises when users modify the template
struct.
This is most important when a watching source is involved, as we now
have a long-lived reference to our template struct.
A natural way users will try to use the `Fill()` method (that we had
failed to anticipate) was to pass the template variable to that struct
directly.
Without this deep-copy, using `Fill()` in this way is:
- thread unsafe, since the watcher assumes that value is immutible and
hence is read without synchronization
- surprising, since the current config becomes the default config,
making removal of fields from config files default to the existing
value, rather htan the normal default that was passed (as the
base-layer) to dials. …
=> Config: deepcopy the template value

ez/ez.go, ez/ez_test.go, sourcewrap/transforming_source.go, sourcewrap/transforming_source_test.go, testhelper/testconfig.yaml, transform/set_slice_mangler.go, transform/set_slice_mangler_test.go
This adds the `SetSliceMangler` that allows us to easily parse lists in formats like JSON, YAML, or TOML into go "sets," commonly implemented as `map[T]struct{}`.  In the `ez` package this option will be enabled by default and can be disabled by adding the `WithAutoSetToSlice` option.
It also fixes a bug in the `TransformingDecoder` that was omitting a necessary call to `ReverseTranslate`.
=> SetSliceMangler

env/env_test.go, flag/flag_test.go, pflag/pflag_test.go, transform/flatten_mangler.go, transform/flatten_mangler_test.go
Fix bug in flatten mangler where nested fields in embedded structs were flattened as anonymous fields. This results in a panic `panic: reflect: embedded type with methods not implemented if type is not first field` for embedded fields of type `time.Time` because that field was now a top level embedded field. This PR unembeds the embedded fields in the flatten mangler and adds fields with `time.Time` type in embedded struct tests
=> Unembed the anonymous fields in flatten mangler

ez/ez.go
Add a pflag specific option in the ez package. The implementation is general so we can substitute any sources for the flag package and add more source options in the future
=> pflag option in ez package

env/env.go, env/env_test.go
Remove underscores because none of the other source-specific struct tags
have no separators.
=> Make `dialsenv` Struct Tag Consistent

parse/map_test.go, parse/split_map.go, parse/split_string_slice.go, parse/string_set_test.go, parse/string_slice_test.go
Allow almost all printing characters when parsing `map[string]string`, `map[string]struct{}`, `map[string][]string` and `[]string` types. This will allow colons (`:`) in slice and set-types, and `/`s, `.`s, mixed numbers and letters and currency/special characters in all types.
This does specifically disallow all types of quotes and whitespace from being unquoted.
=> Allow more characters in unquoted strings in parsed maps and slices

dials.go, dials_test.go, ez/ez.go, ez/ez_test.go, sourcewrap/blank.go
When using a watching source, it's currently possible to end up with an invalid configuration, and there's no way to prevent that from being extracted in everything touching the config `View()` method.
This PR adds a new `VerifiedConfig` interface to the top-level package and moves the `Config()` function to a `Params` struct that contains one field (for now). That single field is a callback to execute upon verification (or stacking) failure.
Additionally, this fixes a segfault when using the blank source in watching mode because it failed to store the context it was passed. (this was uncovered while updating the `ez` package to take advantage of the new mechanism)
=> VerifiedConfig interface, Watcher error handing and plumbing

dials.go, dials_test.go, env/env.go, file/file.go, flag/flag.go, pflag/pflag.go, sourcewrap/blank.go, sourcewrap/blank_test.go, sourcewrap/transforming_source.go, static/static.go
Some `Source` implementations will need to make external requests, and as such should have contexts passed to their `Value()` methods.
Add a `context.Context` argument to the `Value` method on the `Source` interface and update `Config()` to call it with a context that's cancelled on function exit (document this behavior).
This PR fixes the main blocker for `Source` interface stabilization. (a future PR will make some adjustments to the `Watcher` interface)
=> dials: Add context arg to Value() on Source

file/file.go
Tactical fix for a rather severe bug.
I'll do some more significant test construction in another PR. Additionally, this file will need some adjustment when we overhaul the Watcher interface.
=> file: fix segfault in watcher when logger is nil

dials.go, dials_test.go, file/file.go, sourcewrap/blank.go, sourcewrap/blank_test.go, sourcewrap/transforming_source.go
Create a WatchArgs interface for the third argument to Watch() and a base implementation.
Convert the existing implementations of `Watcher` to support the new interface definition.
Tighten the contract on the `Blank` source while we're in there.
=> dials: Update Watcher Interface to use an interface arg

dials.go, dials_test.go, ez/ez.go, ez/ez_test.go, sourcewrap/blank.go
It's common that we would have some required values that might only be
set in the config file.  Previously when using the EZ package, the
`VerifiedConfig` interface was running on the initial stacking before
the config file had a chance to load values in to the overall values.
This allows us to skip the initial verification and wait until the file
is (optionally) considered before running verification.
=> Improve Verification in EZ

ez/ez.go, ez/ez_test.go, tagformat/reformat_tags.go, tagformat/reformat_tags_test.go, testhelper/testconfig.yaml
To avoid having to specify `dials` tags just to get consistent
transformations from Go-case to another strategy, provide a way for the
user to provide an additional mangler to alter the casing.
=> Add File Key Casing to ez

parse/complex.go, parse/complex_go115.go, parse/complex_test.go, transform/string_casting_mangler_test.go
Since go >= 1.15 has strconv.ParseComplex, let's delegate to that where
available.  strconv is also a bit stricter on the format of the complex
number string, so adjust tests to reflect that.  Since few (if any)
people are using this, it shouldn't matter much.
=> Complex Parsing

pflag/pflag.go, pflag/pflag_test.go
Float32s were not handled correctly.  This partially fixes that, though
we will revisit the conversion logic later.
=> PFlag Float32 Handling

tagformat/expand_tags.go, tagformat/reformat_tags.go, transform/transformer.go
Clean up type-handling when dealing with slices.
The struct-tag modifying manglers were playing a bit fast and loose with
their types. That was partially fixed in a previous change.
Actually set the correct types when slices are nil.
=> Fix slice-type-field handling for env source

cb_mgr.go, dials.go, dials_test.go, ez/ez.go, file/file.go, sourcewrap/blank.go
This provides two capabilities:
- When a watching source exits, or is unusable for some reason going
forward, it can call `Done()`, thus letting the monitor() goroutine
shutdown if all other sources are done. (independent of context
cancelation)
- When a source encounters an error that an application may be
interested in, it can call WatchError to bubble it up.
Running user callbacks is always a little dicey. They can block for
indefinite periods and gum of the functioning of an otherwise-functional
system.
Add a callbackMgr type with a runCBs method which will run in its own
goroutine and actually executes user callbacks.
The monitor closes the callback channel upon its exit, so we don't
need to worry about the callback channel hanging around indefinitely.
Let it finish handling any …
=> Watcher error reporting and dials callback manager

cb_mgr.go, dials.go, dials_test.go
Add a callback that's called just after installing a new configuration.
This eliminates the need for most use-cases to use an additional
goroutine to watch for config changes/updates.
The callback gets both the old and the new configs so clients can
differentially update other datastructures.
Since this new callback is executed by the callback manager goroutine,
and we try to keep callback execution serial, NewConfigHandler
implementations should be short to moderately long-running. (if they
take longer than the interval between updates to the config events
will back up)
=> OnNewConfig callback

.github/workflows/go.yml, parse/complex.go, parse/complex_go115.go, parse/complex_test.go
Update the list of go versions with which we run tests.
Now 1.16 and 1.17.
Also update the setup-go and checkout helpers.
Note: we could add 1.18.0-beta1 to the list of versions, but that broke
on macos when I tested it. We can wait until 1.18 is actually released
to include 1.18.
Update the build tag constraints in the `complex` package to match `gofmt` output for more recent versions. (1.17+)
=> actions: test with current go versions  (1.16 and 1.17)

go.mod, go.sum
Resolve CVE-2019-11254 alert on the dials repo by updating the yaml
dependency.
https://github.com/advisories/GHSA-wxc4-f4m6-wwqv
=> gomod: update gopkg.in/yaml.v2

.github/workflows/go.yml, cb_mgr.go, dials.go, dials_test.go, env/env_test.go, ez/ez.go, ez/ez_test.go, file/file.go, file/file_test.go, flag/flag.go, flag/flag_test.go, go.mod, go.sum, integrationtests/case_conversion_transformer_test.go, json/json_test.go, pflag/pflag.go, pflag/pflag_test.go, sourcewrap/blank_test.go, sourcewrap/transforming_source_test.go, toml/toml_test.go, yaml/yaml_test.go
Clean up the top-level interface a bit by using go 1.18 generics. This
adds a bunch of type-safety, and eliminates a few pitfalls.
I'm leaving Fill() and Events() for now, but I'll remove them in a later
change. (I didn't want to update all the tests yet.)
Update tests to remove type-asserts and convert some template-values (of type `interface{}`/`any`) to use callbacks so the config-type is statically available at compile-time when `dials.Config` or `(dials.Param).Config()` is called.
Two parts:
- easy: add type-parameters to the top-level functions so we get the
right types passed down to dials.Config and friends.
- annoying: Unfortunately, for go 1.18, type-inference on
generic-parameters doesn't look at return values and where they're
assigned, so if we use the simple, straightforward …
=> Go 1.18 generics/type-parameters

ez/ez.go, ez/ez_test.go
Improve type-safety and make option-discovery significantly easier by directly exposing the parameters struct.
=> ez: use a params struct instead of options

dials.go, dials_118.go, dials_119.go
The next change will introduce a way to register (and unregister)
callbacks at runtime, with active watchers. To decided whether or not to
immediately call the callback with the current config version. In
particular, it's likely that the caller used a specific version for
setting up the structs/objects that will be manipulated by the callback.
That config-version is the relevant version.
The new CfgSerial type includes a backpointer to the version it refers
to so if the new-config callback needs to deliver a new configuration,
because the "current" version may be later. This way we don't need to
hold onto all versions we've ever seen in order to deliver a catch-up
new-config callback.
=> dials: add ViewVersion to eliminate races in callback registration.

cb_mgr.go, dials.go, dials_test.go
In many processes that need callback streams, the component that will
consume the callbacks needs some initial configuration during
construction.
This produces a paradox when constructing the New Config callback to
insert into the Params struct.
To resolve this, one have two options:
- Create a dummy callback with some synchronization and safety-checks
so one can register the new callback with that other type later.
- Update Dials so it supports runtime callback registration.
Notably, this implementation uses the new CfgSerial type to provide the
necessary safety-checks and guarantee that if one consumes config
version 3, but while object setup is ongoing, versions 4, 5, and 6 come
along, the callback will only be called with oldCfg from version 3, and
newCfg from version 6.
This …
=> dials: runtime callback (un)registration

dials.go, ez/ez.go, ez/ez_test.go, sourcewrap/blank.go, sourcewrap/blank_test.go
Blank has been almost impossible to use correctly, with only a few
(constrained) cases where it can be used safely without having terrible
races (hence the complexity in the `ez` package wrapping it).
Fix this by adding a BlockingReportNewValue method to the `WatchArgs`
interface that returns any errors in stacking or validation to the
caller, (and returns successfully if the new config has been
successfully installed)
With the last few changes, the building-blocks which ez is wrapping
and/or working with are much more robust and easier to use.
Update ez to reflect this new state:
- eliminate the extra channels now that Blank blocks and returns
errors.
- register the OnNewConfig callback at the end, just before returning.
- rename `p` to `dp` to eliminate some confusion with `params`
=> dials/blank: Add/use BlockingReportNewValue

decoders/yaml/yaml_test.go, transform/transformer.go, transform/transformer_test.go
When recursively unmangling structs with ReverseTransform construct the mangled type for interacting with the intermediate types.
This is a partial revert of 9ffa9007c3918ec9cb214094f6bd9dec7e2bdf2b. I misunderstood the ordering of the code unmangling.
This commit adds a test that creates an incompatible struct for the inner type of a slice (converting from 1 to 2 fields). That test failed in an interesting way, and unmasked my mistake.
In maybeRecursivelyUnmangle the type has to be the mangled type so it can be passed to Unmangle after it's recursed into the fields within that field.
Note: this doesn't trigger in many existing test-cases because the mangled type ends up being assignable to the unmangled type.
This PR also adds some sanity-checks so we return errors rather than panicing …
=> Transformer: Construct the right recursive types

.github/workflows/go.yml, cb_mgr.go
Callbacks were previously stored in a map, which made their execution order undefined.  Instead, store the callbacks in a slice and execute them in the order they were registered.  This has the unfortunate side effect of making callback deregistration O(n) instead of O(1), but that's probably an acceptable tradeoff.
Also, update github actions to build with go 1.19 now that we're passed the release candidate stage.
=> Deterministic Callback Order

ez/ez_test.go, transform/set_slice_mangler.go, transform/set_slice_mangler_test.go
Also address a De Morgan's law nit from staticcheck in the guard
For dials' field-stacking to work, we need nil-slices to convert to nil-maps. Add an explicit check so a nil/missing slice/list doesn't turn into an empty map, which is semantically different in that Dials' stacking code sees empty as "specified, but empty", while nil is interpreted as "unspecified".
As a result, in the former case that field in the config is cleared, and in the latter case it's inheritted from the next layer down. (possibly the default in the template struct)
=> transform: propagate nil slice in SetSliceMangler

cb_mgr.go, dials.go, dials_118.go, dials_119.go, dials_test.go
Add a way to delay the initial Verify() call, so users can do multi-step initialization which have intermediate states that are not guaranteed to pass the Verify() method (usually involving multiple blank sources).
After initialization is complete, the user can call VerifyEnable() to get the current config and enable verification.
=> dials: add DelayInitialVerification mode

sources/flag/flag.go, sources/flag/flag_test.go, sources/flag/flaghelper/complex.go, sources/pflag/pflag.go, sources/pflag/pflag_test.go
When using something like `type MyString string` we need to make sure to convert it to the proper underlying type before sending it on to the flag package.
Fix this for both the flag and pflag packages.
=> Fix Custom Type Handling

go.mod, parse/number.go, parse/parse_string.go, ptrify/ptrify_test.go, sources/env/env.go, sources/env/env_test.go, sources/flag/flag.go, sources/flag/flag_test.go, sources/pflag/pflag.go, sources/pflag/pflag_test.go, tagformat/caseconversion/case_conversion.go, transform/flatten_mangler.go, transform/string_casting_mangler_test.go
Clean up all the staticcheck warnings:
```
$ staticcheck ./...
parse/number.go:33:48: error strings should not be capitalized (ST1005)
parse/number.go:62:48: error strings should not be capitalized (ST1005)
parse/number.go:91:48: error strings should not be capitalized (ST1005)
parse/number.go:105:48: error strings should not be capitalized (ST1005)
parse/number.go:118:48: error strings should not be capitalized (ST1005)
parse/number.go:131:48: error strings should not be capitalized (ST1005)
parse/parse_string.go:10:2: var stringSliceType is unused (U1000)
parse/parse_string.go:11:2: var boolSliceType is unused (U1000)
parse/parse_string.go:12:2: var intSliceType is unused (U1000)
parse/parse_string.go:13:2: var int8SliceType is unused (U1000)
parse/parse_string.go:14:2: var …
```
=> Fix staticcheck Warnings

ez/ez.go, ez/ez_test.go
We're planning to deprecate SkipInitialVerification in favor of the more principled DelayInitialVerification+EnableVerification(). Convert the ez package to the newer scheme.
=> ez: convert to DelayInitialVerification

sources/flag/flag.go, sources/pflag/pflag.go
Types that are not explicitly handled currently error out, requiring a bunch of `dialsflag:"-"` spam. Fix this by continuing the loop when these are encountered.
=> flags/pflags: skip registering flags on some types

parse/integral_slice.go, parse/integral_slice_test.go
Support functions for integral-type slice-typed flags.
Support a simple comma-separated list of integers. Let
strconv.Parse{Int,Uint} pick the base so we naturally support Go's
format for binary, hex and octal.
Use generics so we only have one implementation for each of signed and
unsigned ints.
=> parse: add integral-slice type parsing support

sources/flag/flag.go, sources/flag/flag_test.go, sources/flag/flaghelper/ints.go, sources/flag/flaghelper/uints.go
Also, add uintptr support.
Extend the existing test cases to be comprehensive over the set of
integer-types we support as well as integer slices.
=> flag: support for integral slices

sources/pflag/pflag.go, sources/pflag/pflag_test.go
Mirroring the flag support, add support for integral-typed flags.
Also, fix a bug in the pflag vistor callback that paniced due to an
incorrect conversion. (exercised via the new the uintptr support)
=> pflag: add integral-slice and uintptr support

transform/flatten_mangler.go, transform/flatten_mangler_test.go
Fix the FlattenMangler so it doesn't populate intermediate struct-fields
of pointer-type. Since pointerification pretty much always converts
these fields to pointers, this is the common case.
There was a bit of missing accounting, so with two structs:
```go
type A struct {
Field1 *int
Field2 *string
}
struct B struct{
Field3 *A
}
```
`B.Field3` was always populated with the zero-value, even if both
`B.Field3_Field1` and `B.Field3_Field2` are `nil`.
This change fixes the case where all underlying fields are `nil`, and
prevents those intermediate fields from getting set to non-`nil` values.
=> transform: flatten mangler: handle nil subfields

decoders/cue/cue.go, decoders/cue/cue_test.go, decoders/json/json.go, decoders/json/json_test.go, decoders/json/jsontypes/jsonduration.go, decoders/json/jsontypes/jsonduration_test.go
Add a `jsontypes` package with a `ParsingDuration` type that implements `json.Unmarshaler`, making it possible to use both human-friendly strings (`3s`) and integer nanoseconds (for compatibility).
Leverage the new `SingleTypeSubstitutionMangler` to make this substitution in the cue and json decoders (during decoding).
=> json/cue: substitute time.Duration with type using time.ParseDuration

README.md, sources/flag/flag_test.go, sources/flag/flaghelper/ints.go, sources/flag/flaghelper/strings.go, sources/flag/flaghelper/uints.go, sources/pflag/pflag_test.go
It's been a while since it was last updated, and I felt weird adding a
section explaining slice parsing without fixing the complete staleness
of the readme's examples.
- Removed Fill() calls, which are deprecated
- Updated ez package references to use Params
- Removed type-asserts on View() calls
- Removed Events() calls, and updated to the less convoluted
callback-based change-notification mechanism.
Instead of always using the last flag value referenced, merge all values
present.
=> flags/pflags: slice/map flags concat/merge & README update

README.md, common/tags.go, ez/ez.go, ez/ez_test.go, sources/env/env.go, sources/flag/flag.go, sources/pflag/pflag.go, transform/alias_mangler.go, transform/alias_mangler_test.go, transform/transformer.go
AliasMangler
Add a new mangler that allows us to have aliases for dials tags to
facilitate migrating from one name to another seamlessly.  If both the
old name and the new name are set, an error will be returned because the
expectation is that you're using one or the other exclusively.
Also, fix a bug in `ez` where an error thrown by a Source may cause the
process to hang.
And, lastly, specifically exclude TextUnmarshaler implementing types
from mangling.
=> AliasMangler

sources/pflag/pflag.go
Pflag has types for all the integer sizes so we don't need to check for overflowing and thus this code that was inherited from the flag package is unnecessary.
This fixes:
```
sources/pflag.go L495: impossible condition: nil != nil
```
=> Remove Unnecessary Error from pflag

tagformat/caseconversion/case_conversion.go, tagformat/caseconversion/case_conversion_test.go
- provide the ability to augment or replace the set of initialisms that are used
- provide an EncodeCasingFunc for the Go style
- introduce the concept of "atoms" so that Go will not attempt to break up names that we want to be kept together.
=> Improve Go Case Conversion
